### ISSUE TITLE
SBOL Visual Glyphs Unreadable

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SbolStandardWebsite#136]
The SBOL visual glyphs are not readable.  The white space should be reduced so the glyphs are larger, and we should also increase the font size of the text in the labels.  It should be the case that if these cards are put on a slide, they are legible to the audience.

We might also want to split up the sequence glyphs into multiple cards.

**Comment by tcmitchell** [comment]
@cjmyers does this issue refer primarily to the "Sequence Features" image displayed on https://sbolstandard.org/visual-glyphs/ ? If so, we can expand it.

Changes to font size would need to be handled in https://github.com/SynBioDex/SBOL-visual to update https://github.com/SynBioDex/SBOL-visual/blob/master/sampler/Sequence%20Features.png which is the image that is displayed on https://sbolstandard.org/visual-glyphs/

Similarly, since this is simply a linked image, we cannot split up the sequence glyphs into multiple cards.

**Comment by cjmyers** [comment]
Yes, it is the image on that page.  Expanding should help.  It seems there is space in the boxes to change the size of the glyphs though as well.  Agree that changes may also need to be made to the card(s) to make these more legible.

**Comment by tcmitchell** [comment]
> Yes, it is the image on that page. Expanding should help.

I will do that

> It seems there is space in the boxes to change the size of the glyphs though as well.

You should open an issue at https://github.com/SynBioDex/SBOL-visual for that, and for any other changes to the image itself. When the image changes there, it will automatically update on https://sbolstandard.org/visual-glyphs/. Magic.

**Comment by cjmyers** [comment]
I've logged an issue there.
